import { expect, test} from "@playwright/test";
import path from "path";
import { esatLogin } from "../../pages/eSatLogin";
import { esatCredentials } from "../../pages/eSatLogin";
import { SowSteps } from "../../pages/SowSteps";



//LOGIN
test.use(esatCredentials);

test.beforeEach(async ({ page }) => {
  await esatLogin(page);
});

//TESTS
test("Scope of Work - Send to Committee", async ({ page }) => { 
    test.setTimeout(200000);

    const dialogs = {
        homogenity: page.locator('mat-dialog-container').filter({ has: page.getByRole('button', { name: 'İrəli' }) }),
        ai: page.locator('mat-dialog-container').filter({ has: page.getByRole('button', { name: 'Təsdiq edin' }) }),
    };

    const steps = new SowSteps(page);
    
    await page.goto("/scope-of-works/list");
    await page.getByRole('button', { name: 'Yarat' }).click();
    await page.getByRole('textbox', { name: 'Satınalma predmeti' }).fill('AutoGenerated');
    await page.getByRole('combobox', { name: 'Satınalma metodu Satınalma' }).click();
    await page.getByRole('option', { name: 'Kotirovka sorğusu', exact: true }).click();
    await page.locator('#mat-select-value-5').click();
    await page.getByRole('option', { name: 'Mal' }).click();
    await page.getByRole('dialog', { name: 'Şərtlər toplusunun yaradılması' }).click();
    await page.getByRole('textbox', { name: 'Ehtimal olunan qiymət' }).fill('59000');
    await page.getByRole('dialog', { name: 'Şərtlər toplusunun yaradılması' }).click();
    await page.locator('input[type="file"]').setInputFiles(path.join(__dirname, 'playwright-test.pdf'));
    await page.getByRole('button', { name: 'Yarat' }).click();
    await page.getByText('Satınalma planı maddəsini seçin Elan sətri *').click();
    await page.locator('.cdk-virtual-scroll-viewport').first().click();
    // await page.getByText('Qoşma').click();
    await page.locator('input[type="file"]').setInputFiles(path.join(__dirname, 'playwright-test.pdf'));
    await page.getByRole('button', { name: 'Yadda saxla' }).click();
    await page.locator('mat-form-field').filter({ hasText: 'Təkliflərin cəlb edilməsi bar' }).getByLabel('Open calendar').click();
    await page.locator('td').filter({ hasText: '7' }).first().click();
    await page.getByRole('button').filter({ hasText: 'done' }).click();
    await page.locator('mat-form-field').filter({ hasText: 'Təkliflərin təqdim edilmə' }).getByLabel('Open calendar').click();
    await page.getByRole('button', { name: 'Next month' }).click();
    await page.locator('td').filter({ hasText: '20' }).click();
    await page.getByRole('button').filter({ hasText: 'done' }).click();
    await page.getByRole('button', { name: 'Yadda saxla' }).click();
    await page.getByText('Seçim edin Satınalmaya dair s').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByRole('textbox', { name: 'Satınalmaya dair sənədlərin t' }).click();
    await page.getByRole('textbox', { name: 'Satınalmaya dair sənədlərin t' }).fill('test');
    await page.getByText('Seçim edin Dövlət mənsubiyyə').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.locator('div').filter({ hasText: /^İştirakı məhdudlaşdırılan ölkələr və ya xarici təchizatçılar barədə məlumat \*$/ }).nth(4).click();
    await page.getByRole('textbox', { name: 'İştirakı məhdudlaşdırılan ölk' }).fill('test');
    await page.getByRole('combobox', { name: 'Subpodratçının cəlb edilməsin' }).click();
    await page.getByRole('listbox', { name: 'Subpodratçının cəlb edilməsin' }).getByText('Bəli').click();
    await page.getByRole('textbox', { name: 'Subpodratçı üçün tələblər' }).click();
    await page.getByRole('textbox', { name: 'Subpodratçı üçün tələblər' }).fill('test');
    await page.getByRole('combobox', { name: 'Birgə fəaliyyət üzvlərinin' }).click();
    await page.getByRole('option', { name: '2' }).click();
    await page.getByRole('combobox', { name: 'Yetərsay və maliyyələşdirmə ə' }).click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.locator('div').filter({ hasText: /^Uyğunluq sənədlərinin yenidən təqdim edilməsi halları \*$/ }).nth(5).click();
    await page.getByRole('textbox', { name: 'Uyğunluq sənədlərinin yenidən' }).fill('test');
    await page.getByRole('textbox', { name: 'Alternativ texniki həllərin' }).click();
    await page.getByRole('textbox', { name: 'Alternativ texniki həllərin' }).fill('test');
    await page.getByRole('button', { name: 'Yadda saxla' }).click();
    await page.getByRole('textbox', { name: 'Uyğunluğa dair qeydlər' }).click();
    await page.getByRole('textbox', { name: 'Uyğunluğa dair qeydlər' }).fill('test');
    await page.getByRole('button', { name: 'Yadda saxla' }).click();
    await page.getByRole('textbox', { name: 'Müqavilənin icra müddəti (bu' }).click();
    await page.getByRole('textbox', { name: 'Müqavilənin icra müddəti (bu' }).fill('35');
    await page.getByText('Seçim edin İstehsalçı icazəsi').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByRole('textbox', { name: 'İstehsalçının icazəsi tələb' }).click();
    await page.getByRole('textbox', { name: 'İstehsalçının icazəsi tələb' }).fill('test');
    await page.getByRole('combobox', { name: 'Satış sonrası xidmət Seçim' }).click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByRole('textbox', { name: 'İstismar müddəti (ehtiyat' }).click();
    await page.getByRole('textbox', { name: 'İstismar müddəti (ehtiyat' }).fill('test');
    await page.getByRole('textbox', { name: 'Digər tələblər' }).click();
    await page.getByRole('textbox', { name: 'Digər tələblər' }).fill('test');
    // await page.getByRole('tabpanel', { name: '6 Satınalma predmetinə dair t' }).getByText('Qoşma').click();
    await page.getByRole('tabpanel', { name: '6 Satınalma predmetinə dair t' }).locator('input[type="file"]').setInputFiles(path.join(__dirname, 'playwright-test.pdf'));
    await page.getByRole('button', { name: 'Yadda saxla' }).click();
    await page.getByRole('spinbutton', { name: 'Təklifin qüvvədə olma müddəti' }).click();
    await page.getByRole('spinbutton', { name: 'Təklifin qüvvədə olma müddəti' }).fill('35');
    await page.getByRole('textbox', { name: 'Təklifin qiymətində nəzərə al' }).click();
    await page.getByRole('textbox', { name: 'Təklifin qiymətində nəzərə al' }).fill('test');
    await page.getByRole('button', { name: 'Yadda saxla' }).click();

    await steps.fillBomRow({
    name: 'Adobe Acrobat',
    description: 'Adobe Premiere Pro license',
    quantity: '1',
});

    await page.getByRole('cell', { name: 'Seçin' }).getByRole('combobox').selectOption('ədəd');
    await page.getByRole('button', { name: 'Axtar' }).click();
    await page.getByRole('button', { name: 'Toggle Canlı Bitki və Heyvan' }).click();
    await page.getByRole('button', { name: 'Toggle Canlı heyvanlar' }).click();
    await page.getByRole('button', { name: 'Toggle Ev heyvanları', exact: true }).click();
    await page.locator('#mat-dialog-1').click();
    await page.locator('mat-radio-button', { hasText: 'Pişiklər' }).click();
    await expect(page.getByRole('radio', { name: 'Pişiklər' })).toBeChecked();

    await page.getByRole('button', { name: 'Təsdiq edin' }).click();


    await page.getByRole('button', { name: 'Yadda saxla', description: 'Yadda saxla' }).click();

    await steps.saveStep('İş həcmləri cədvəli');

    // Homogenity Dialog
    await expect(dialogs.homogenity).toBeVisible({ timeout: 50000 });
    await dialogs.homogenity.getByRole('button', { name: 'İrəli' }).click();

    // AI Check dialog
    await expect(dialogs.ai).toBeVisible({ timeout: 50000 });
    await dialogs.ai.locator('mat-checkbox', { hasText: 'tanış oldum' }).click();

    const confirmButton = dialogs.ai.getByRole('button', { name: 'Təsdiq edin' });
    await expect(confirmButton).toBeEnabled();
    await confirmButton.click();

    await expect(dialogs.ai).toBeHidden();
    await steps.waitForLoader();

    await page.locator('#mat-input-58').fill('Urfan');
    await page.locator('#mat-input-58').press('Tab');
    await page.locator('#mat-input-58').fill('Urfan');
    await page.locator('#mat-input-59').fill('QAAA');
    await page.locator('#mat-input-59').press('Tab');
    await page.locator('#mat-input-59').fill('QAAA');
    await page.getByPlaceholder('example@domain.com').fill('2@2');
    await page.getByPlaceholder('example@domain.com').press('Tab');
    await page.getByPlaceholder('example@domain.com').fill('2@2');
    await page.locator('#mat-input-61').fill('50 728 10 00');
    await page.getByTitle('Yadda saxla').click();
    await page.locator('app-contact-person-step > .d-flex.justify-content-end.mt-4 > .mat-focus-indicator').click();
    await page.getByLabel('Ödəmələr *').click();
    await page.getByLabel('Ödəmələr *').fill('test');
    await page.getByLabel('Ödəmələr *').press('Tab');
    await page.getByLabel('Ödəmələr *').fill('test');
    await page.getByLabel('Avans *').fill('25');
    await page.getByLabel('Avans (mikro və kiçik').click();
    await page.getByLabel('Avans (mikro və kiçik').fill('25');
    await page.locator('div').filter({ hasText: /^Satınalma müqaviləsinin qüvvəyə minmə qaydaları \*$/ }).nth(4).click();
    await page.getByLabel('Satınalma müqaviləsinin qüvvə').fill('test');
    await page.getByLabel('Satınalma müqaviləsinin qüvvə').press('Tab');
    await page.getByLabel('Satınalma müqaviləsinin qüvvə').fill('test');
    await page.getByLabel('Müqaviləyə dəyişiklik *').fill('test');
    await page.getByLabel('Müqaviləyə dəyişiklik *').press('Tab');
    await page.getByLabel('Müqaviləyə dəyişiklik *').fill('test');
    await page.getByLabel('Sığorta *').fill('test');
    await page.getByLabel('Sığorta *').press('Tab');
    await page.getByLabel('Sığorta *').fill('test');
    await page.getByLabel('Çatdırılma, o cümlədən tətbiq').fill('test');
    await page.locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.getByLabel('Tətbiq olunan əlavə hüquqi normalar və sənədlər *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Tətbiq olunan əlavə hüquqi normalar və sənədlərin detalları *').click();
    await page.getByLabel('Tətbiq olunan əlavə hüquqi normalar və sənədlərin detalları *').fill('test');
    await page.getByLabel('Təchizatçının əlavə öhdəlikləri *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Təchizatçının əlavə öhdəliklərin detalları *').click();
    await page.getByLabel('Təchizatçının əlavə öhdəliklərin detalları *').fill('test');
    await page.getByLabel('Hüquqi və təşkilati məsələlər, icazələr və razılaşmalar *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Satınalan təşkilat tərəfindən').click();
    await page.getByLabel('Satınalan təşkilat tərəfindən').fill('test');
    await page.getByLabel('İcra təminatı *').getByText('Seçim edin').click();
    await page.getByRole('listbox', { name: 'İcra təminatı *' }).getByText('Bəli').click();
    await page.getByLabel('İcra təminatına dair tələblər').click();
    await page.getByLabel('İcra təminatına dair tələblər').fill('test');
    await page.getByLabel('Qablaşdırma və sənədləşmə *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Qablaşdırma və sənədləşmə bar').click();
    await page.getByLabel('Qablaşdırma və sənədləşmə bar').fill('test');
    await page.getByLabel('Daşınma *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Daşınma ilə bağlı digər tələ').click();
    await page.getByLabel('Daşınma ilə bağlı digər tələ').fill('test');
    await page.getByText('Seçim edin Əlavə xidmətlər *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.locator('div').filter({ hasText: /^Əlavə xidmətlərin detalları \*$/ }).nth(4).click();
    await page.getByLabel('Əlavə xidmətlərin detalları *').fill('test');
    await page.getByLabel('Sınaq və (və ya) yoxlamalar *').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Sınaq və (və ya) yoxlamalar detalları *').click();
    await page.getByLabel('Sınaq və (və ya) yoxlamalar detalları *').fill('test');
    await page.getByLabel('Sınaq və (və ya) yoxlamaların aparılacağı yer *').click();
    await page.locator('.mat-option-text').first().click();
    await page.getByLabel('Sınaq və (və ya) yoxlamaların aparılacağı yerin ünvanı *').click();
    await page.getByLabel('Sınaq və (və ya) yoxlamaların aparılacağı yerin ünvanı *').fill('test');
    await page.getByLabel('Open calendar').click();
    await page.locator('td').filter({ hasText: '20' }).click();
    await page.getByRole('button').filter({ hasText: 'done' }).click();
    await page.locator('div').filter({ hasText: /^Müqavilənin icrasına başlama detalları$/ }).nth(5).click();
    await page.getByLabel('Müqavilənin icrasına başlama detalları').fill('test');
    await page.getByLabel('Seçim edin').click();
    await page.getByRole('option', { name: 'Bəli' }).click();
    await page.getByLabel('Azərbaycan Respublikasının ə').click();
    await page.getByLabel('Azərbaycan Respublikasının ə').fill('test');
    await page.getByLabel('Çatdırılmanın və təchizatçı t').click();
    await page.getByLabel('Çatdırılmanın və təchizatçı t').fill('test');
    await page.getByLabel('2 Müqavilənin xüsusi şərtləri').locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.getByLabel('Сərimənin gündəlik faizi (%) *').click();
    await page.getByLabel('Сərimənin gündəlik faizi (%) *').fill('0');
    await page.getByLabel('Сərimənin gündəlik faizi (%) *').press('Tab');
    await page.getByLabel('Maksimum faiz həddi (%) *').fill('0');
    await page.getByLabel('Maksimum faiz həddi (%) *').press('Tab');
    await page.getByLabel('Gecikdirilmiş ödənişə görə cə').fill('0');
    await page.getByLabel('Gecikdirilmiş ödənişə görə cə').press('Tab');
    await page.getByLabel('Dəbbə pulu *').fill('0');
    await page.getByLabel('Dəbbə pulu *').press('Tab');
    await page.getByLabel('Təmir və ya dəyişdirmə müddə').fill('35');
    await page.getByLabel('Təmir və ya dəyişdirmə müddə').press('Tab');
    await page.getByLabel('Təmir və ya dəyişdirmə müddə').fill('35');
    await page.getByLabel('Zəmanət müddəti (gün) *').fill('test');
    await page.getByLabel('3 Cərimə və zəmanət Info').locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.locator('#mat-input-84').click();
    await page.locator('#mat-input-84').fill('test');
    await page.getByLabel('4 Satınalan təşkilatın sə').locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.getByLabel('Bankı seçin *').click();
    await page.getByRole('option', { name: 'Leyla Bank (H/h 24234)' }).click();
    await page.getByLabel('Bank məlumatları').locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.getByLabel('Kimə *').click();
    await page.getByLabel('Kimə *').fill('Leylaya');
    await page.getByLabel('Poçt kodu *').click();
    await page.getByLabel('Poçt kodu *').fill('1111');
    await page.getByLabel('Telefon *').click();
    await page.getByLabel('Telefon *').fill('50 728 10 00');
    await page.getByLabel('Elektron poçt ünvanı *').click();
    await page.getByLabel('Elektron poçt ünvanı *').fill('1@1');
    await page.locator('.mat-form-field-infix.ng-tns-c80-181').click();
    await page.getByLabel('Mobil telefon').fill('4066996');
    await page.locator('.mat-form-field-infix.ng-tns-c80-183').click();
    await page.getByLabel('Veb səhifə').fill('test.com');
    await page.getByLabel('Bildirişlər üçün ünvan').locator('button').filter({ hasText: 'Yadda saxla' }).click();
    await page.locator('button').filter({ hasText: 'add Şablonu seçin' }).click();
    await page.getByRole('button', { name: 'Sonrakı səhifəyə keçid' }).click();
    await page.getByRole('button', { name: 'Sonrakı səhifəyə keçid' }).click();
    await page.getByRole('button', { name: 'Sonrakı səhifəyə keçid' }).click();
    await page.getByRole('dialog', { name: 'Satınalma komissiyası ş' }).click();
    await page.locator('.mat-row').filter({hasText:"Urfan's Committee"}).locator('.mat-radio-button').click();
    await page.getByRole('button', { name: 'Təsdiq edin' }).click();
    await page.locator('app-tender-committee-sow').filter({ hasText: 'CAVİD NƏZƏROV' }).locator('mat-radio-button').click();
    await page.getByLabel('', { exact: true }).check();
    // await page.getByText('Qoşma').click();
    await page.locator('input[type="file"]').setInputFiles(path.join(__dirname, 'playwright-test.pdf'));
    await page.locator('button').filter({ hasText: 'İrəli' }).click();
    await page.getByRole('button', { name: 'Sİ ilə yoxla' }).click();
    await page.locator('.mat-checkbox-inner-container').click();
    await page.getByRole('checkbox', { name: 'Təqdim edilən məlumatla tan' }).check();
    await page.getByRole('button', { name: 'İrəli' }).click();
    await page.getByRole('textbox', { name: 'Şərh' }).fill('');
    await page.getByRole('dialog', { name: 'Rəy bildirilməsi' }).click();
    await page.getByRole('button', { name: 'Keç' }).click();
    await page.getByRole('dialog', { name: 'Şərtlər toplusu' }).click();
    await page.locator('.mat-radio-button', { hasText: 'Asan İmza' }).click();
    await page.getByRole('button', { name: 'Komissiyaya göndər' }).click();

});